spring:
  application:
    name: Ecom

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb?options=-c%20TimeZone=Asia/kolkata
    username: embarkx
    password: embarkx

  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

management:
    endpoints:
      web:
        exposure:
          include: beans, health
    endpoint:
      health:
        show-details: always
      shutdown:
        access: unrestricted
    info:
      env:
        enabled: true

server:
    shutdown: graceful

info:
    app:
      name: MyNewApp
      description: App built by us
      version: 1.0.0