spring:
  application:
    name: Ecom
    datasource:
      url: jdbc:postgresql://localhost:5432/ecomdb
      username: Root
      password: Root123

    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

management:
    endpoints:
      web:
        exposure:
          include: beans, health
    endpoint:
      health:
        show-details: always
      shutdown:
        access: unrestricted
    info:
      env:
        enabled: true

server:
    shutdown: graceful

info:
    app:
      name: MyNewApp
      description: App built by us
      version: 1.0.0